### ISSUE TITLE
is there UWP and WP8.1 support on xamarin.forms?

### ISSUE THREAD

**Issue by EmilAlipiev** [awslabs/aws-sdk-xamarin#39]
I implemented cognito identity and sync in xamarin PCL project. it works fine in android but when I try in UWP. I am getting an exception. Does that mean it only work for android and ios using xamarin.forms?

```
System.NotImplementedException was unhandled by user code
  HResult=-2147467263
  Message=This functionality is not implemented in the portable version of this assembly. You should reference the AWSSDK.Core NuGet package from your main application project in order to reference the platform-specific implementation.
  Source=AWSSDK.Core
  StackTrace:
       at Amazon.Util.Internal.PlatformServices.ApplicationSettings.GetValue(String key, ApplicationSettingsMode mode)
       at Amazon.CognitoIdentity.CognitoAWSCredentials.GetCachedIdentityId()
       at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String accountId, String identityPoolId, String unAuthRoleArn, String authRoleArn, IAmazonCognitoIdentity cibClient, IAmazonSecurityTokenService stsClient)
       at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String accountId, String identityPoolId, String unAuthRoleArn, String authRoleArn, RegionEndpoint region)
       at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String identityPoolId, RegionEndpoint region)
```

**Comment by tawalke** [comment]
@EmilAlipiev The Xamarin SDK has migrated to the .NET SDK https://github.com/aws/aws-sdk-net This supports more platforms, you can add functionality via NuGet of individual services. You can read about the Xamarin part of the SDK here: http://docs.aws.amazon.com/mobile/sdkforxamarin/developerguide/ and the base SDK https://aws.amazon.com/documentation/sdk-for-net/

**Comment by EmilAlipiev** [comment]
Hi, 

Sorry but this doesnt make it clear about my exception. AWS claims and advertises that SDK supports xamarin forms for all platforms.

> Portable Class Library
> 
> This release of the AWS SDK for .NET adds support for Portable Class Library projects, which allow you to target multiple platforms including Windows Store, Windows Phone, and Xamarin on iOS and Android. More information on this can be found here.

  Obviously UWP and WP8.1 are not support using PCL library, at least for AWS Cognito. I cant even find a clear document how the things should work with UWP in a Xamarin Forms project. 

Thank you for your help
